### ISSUE TITLE
Get Arduino Working

### ISSUE THREAD

**Issue by CBenshoof** [RootCellar/LHSPass#4]
Arduino is up-and-running on the tablet.  Successfully reads RFID tags, printing 6-character RFID codes to Serial.  Tags read consistently.

**Comment by RootCellar** [comment]
Nice. This program will likely be working by the end of the week. Have you been seeing my twitter status update messages?

**Comment by CBenshoof** [comment]
I have yes - approximately 2,000,000 tweets today :)   You've been busy!
